# Funding links for Diablo

# GitHub Sponsors (recommended)
github: Anlominus

# Other funding platforms (optional)
# Example:
# patreon: username
# open_collective: project-name
# ko_fi: username
# tidelift: platform/framework
# community_bridge: project-name
# liberapay: username
# issuehunt: username/repo
# otechie: username
# lfx_crowdfunding: project-name
# polar: project-name
# buy_me_a_coffee: username

# Custom links
custom: 
  - ['PayPal', 'your-paypal-link-here']
  - ['Bitcoin', 'your-bitcoin-address-here']

