#!/bin/sh
#!/bin/bash
#!/usr/bin/bash
#!/usr/bin/env bash
#!/data/data/com.termux/files/usr/bin/bash
###############################################
# Name : AnLoMinus ~ Diablo
# Description : Diablo ~ enter you target and get Markdown Report.
Anlominus="AnLoMinus"
# Last UPDATE : 06-10-2022
# Aouther: AnLoMinus ~> RhytMix ~> Diablo
# Skils: Best Copywriter IN the COSMOS!
# BIG THANX TO ALL COMUNITY THAT SHARE ALL THAT FREE GREAT SCRIPTS
# CREDIT: To All World Creators free Scripts & Tools
# Location: Made With LOVE IN ISRAEL !
# Source: https://github.com/AnLoMinus/Diablo
###############################################
. ../HacKingPro/HacKingPro-Parts/Main/HacKingPro-Planning
clear
# CODE Functions
# checking for system package manager
if [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ `command -v brew` ]; then
  pac="brew"
  system="mac"
  sudo=""
elif [ `command -v apt` ]; then
  pac="apt"
  system="linux"
elif [ `command -v apt-get` ]; then
  pac="apt-get"
  system="linux"
elif [ `command -v apk` ]; then
  pac="apk"
  system="linux"
elif [ `command -v yum` ]; then
  pac="yum"
  system="fedora"
fi

pressEnter(){
  press_Enter=$(echo "\n\t\t${LGreen}Press ${BGreen} ENTER\t\t")
  read -p "$press_Enter" read_ENTER
}
DiabloColors(){
##############################################################################
# COLORS AND BACKGROUNDS
##############################################################################
Color_Off='\033[0m' # Text Reset

# Regular Colors
Black='\033[0;30m'  # Black
Red='\033[0;31m'    # Red
Green='\033[0;32m'  # Green
Yellow='\033[0;33m' # Yellow
Blue='\033[0;34m'   # Blue
Purple='\033[0;35m' # Purple
Cyan='\033[0;36m'   # Cyan
White='\033[0;97m'  # White

# Additional colors
LGrey='\033[0;37m'   # Ligth Gray
DGrey='\033[0;90m'   # Dark Gray
LRed='\033[0;91m'    # Ligth Red
LGreen='\033[0;92m'  # Ligth Green
LYellow='\033[0;93m' # Ligth Yellow
LBlue='\033[0;94m'   # Ligth Blue
LPurple='\033[0;95m' # Light Purple
LCyan='\033[0;96m'   # Ligth Cyan


# Bold
BBlack='\033[1;30m'  # Black
BRed='\033[1;31m'    # Red
BGreen='\033[1;32m'  # Green
BYellow='\033[1;33m' # Yellow
BBlue='\033[1;34m'   # Blue
BPurple='\033[1;35m' # Purple
BCyan='\033[1;36m'   # Cyan
BWhite='\033[1;37m'  # White

# Underline
UBlack='\033[4;30m'  # Black
URed='\033[4;31m'    # Red
UGreen='\033[4;32m'  # Green
UYellow='\033[4;33m' # Yellow
UBlue='\033[4;34m'   # Blue
UPurple='\033[4;35m' # Purple
UCyan='\033[4;36m'   # Cyan
UWhite='\033[4;37m'  # White

# Background
On_Black='\033[40m'  # Black
On_Red='\033[41m'    # Red
On_Green='\033[42m'  # Green
On_Yellow='\033[43m' # Yellow
On_Blue='\033[44m'   # Blue
On_Purple='\033[45m' # Purple
On_Cyan='\033[46m'   # Cyan
On_White='\033[47m'  # White
}
DiabloColors
DiabloLogo1(){
DiabloLogo_1="$(echo "
${BRed}                                                 ^${BBlue}:
${BRed}                                                ^!${BBlue}^.
${BRed}                  :.                 .         ^~!${BBlue}~:.                           .
${BRed}               .::^.                .^.        :~~${BBlue}^^.        :.                 .:..:
${BRed}           ....:^^:                .^^:  :.    :~!${BBlue}~^:   ..  .:^.                 .::::...
${BRed}         .:...^^.             .    .^::::^.    ^~7${BBlue}!~:   .::.:.^:                   ......:.
${BRed}      .....::^^           . .!!^^!^:::::::^:...^!?${BBlue}7~:. .:::::.::.:::^!~.             .:...:..
${BRed}      ....:.::            .^^~:!!~~77^::^::^:::~!7${BBlue}7~~::^^:^:.:.:^!!!^:^:.             ......::
${BRed}    .. ....:^           .:^^~~!!^::~!!~~^::^^^:~!7${BBlue}!^^:^^::::~!~!^:^^!!!!^.:.           :. .:.::
${BRed}   ..  .. .:^         ........:?^.:~^~7??7!~^^^^~!${BBlue}~^^^~^!7777^!~::^?7::::...:.         ..  .....
${BRed}    .     .::    ....:^~~^^^:. ::::~^:~!7?JJ7~~^^~${BBlue}^^^^~7YYJ7^:^~^.:!. .:^~~~~~^:.      ::  ....:
${BRed}   ..       .^..::^^:::.:^^..   .:::^:^~~~~7Y?~^~!${BBlue}!~!7YJ!~^^^:^~::::   ..^!~::::::::. .:    ....
${BRed}    .        ..:..:~::.          ::::^^~~7YJ?5JJ~7${BBlue}~~YYYJ5J~~~~~::::       .  :^~!^::^..       ..
${BRed}     .  .          .            .::^~!7!7?P57!7~!J${BBlue}7~!!~?Y?7!~!~~^.:      .     .. ...         .
${BRed}     .                          ^:^~!7777!!!!!7?J5${BBlue}YY7!!7!!77!77!^...     .                   .
${BRed}      ..                        ^:.:^!7?J7~^77!!?P${BBlue}Y7~7?!~!?JJ~:....:    .                   .
${BRed}        .... .                  .  ....:^.:~?Y7777${BBlue}?J??J7~:.^:...   :. .. .            .....
${BRed}             .  . ..   .   .          :::.:^!7?77?${BBlue}J?777~^^....               .  .   . .
${BRed}                                      ^::.:~~!^~~?${BBlue}7~^~~^.:...:
${BRed}                                     .::^:.~!G?5YY${BBlue}5YYP7^..::^^.
${BRed}                                   :::^::::~^7!J?J${BBlue}J77?!~::::^:^:.
${BRed}                                   .:!7^..:!??77??${BBlue}?7?!J7::.::7?!:
${BRed}                                   ^^7J!:.:.~!!!7?${BBlue}77!!7^.:::~!7~~7.
${BRed}                                  !B5^:::...:::~!7${BBlue}7!~^:....::::^PGY.
${BRed}                                 :YP?: .  :.::^::^${BBlue}^:::::.:.. ...~5B7
${BRed}                                 ~!.       :::~^!7${BBlue}?!^^^:..        ^!.
${BRed}                                .           ::::~J${BBlue}J?~::::
${BRed}                                            ...!Y#${BBlue}&#J^.:
${BRed}                                               ~5P${BBlue}#P?.
${BRed}                                                7Y${BBlue}PY^
${BRed}                                                .~${BBlue}7~
${BRed}                                                 .${BBlue}:.
${BRed}                                                  ${BBlue}.
${BRed}                       ██████████    ███            █████     ████
${BRed}                      ░░███░░░░███  ░░░            ░░███     ░░███
${BRed}                       ░███   ░░███ ████   ██████   ░███████  ░███   ██████
${BRed}                       ░███    ░███░░███  ░░░░░███  ░███░░███ ░███  ███░░███
${BRed}                       ░███    ░███ ░███   ███████  ░███ ░███ ░███ ░███ ░███
${BRed}                       ░███    ███  ░███  ███░░███  ░███ ░███ ░███ ░███ ░███
${BRed}                       ██████████   █████░░████████ ████████  █████░░██████
${LRed}                      ░░░░░░░░░░   ░░░░░  ░░░░░░░░ ░░░░░░░░  ░░░░░  ░░░░░░
                                                      ")"

echo "$DiabloLogo_1"
}

#####################################
#------╼╼▰[ Variables ]--╼▰ [ End ] #
#####################################
#-╼▰[ HacKingPro ]-╼▰▰ [ Status ]-╼▰▰ [ Target ]-╼▰▰
TargetStatus(){
  echo "
    ${ORANGE}${faintT}┌──╼${resetT}${BBlue}┤${ORANGE} Target Status ${BBlue}├${ORANGE}${faintT}───────╼${resetT}${BCyan}▰▰▰
    ${ORANGE}${faintT}│
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetIP)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}IP${BBlue}: ${BGreen}${targetIP}
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetDns)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Dns${BBlue}: ${BGreen}${targetDns}
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetName)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Name${BBlue}: ${BGreen}${targetNAME}
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetEmail)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Email${BBlue}: ${BGreen}${targetEmail}
    ${ORANGE}${faintT}|──╼${resetT}${ORANGE} ◈ ${BRed}[${DGrey}$(FunTargetPhone)${BRed}]${BCyan}${faintT}──╼  ${LRed}${faintT}Phone${BBlue}: ${BGreen}${targetPhone}
    ${ORANGE}${faintT}│
    ${ORANGE}${faintT}└───────────────────────────────╼${resetT}${BCyan}▰▰▰
"
}
#-╼▰[ HacKingPro ]-╼▰▰ [ Status ]-╼▰▰ [ Target ]-╼▰▰ ╼▰▰ [ Running ]
TargetStatusRun(){
  ToolStatus=$(echo "
    ${InternetStatus}
    ${BCyan}${faintT}┌──${resetT}${BRed}[${BCyan} ${slowBlink}P${resetT} ${BRed}]${faintT}${BCyan}──${resetT}${BCyan}╼▰ ${BRed}[${faintT}${BCyan} ⚡️ Planning and Scoping 🎯 ${BRed}]${BCyan}${faintT}───────╼${resetT}${BCyan}▰▰▰
    ${BCyan}${faintT}|
    ${BCyan}${faintT}|──${resetT}${BRed}[${DGrey} Full Time ${BRed}]${faintT}${BCyan}──╼${resetT} ${BRed}[${DGrey} $(date) ${BRed}]
    ${BCyan}${faintT}|──${resetT}${BRed}[${DGrey} Current Date ${BRed}]${faintT}${BCyan}──╼${resetT} ${BRed}[${DGrey} ${CurrentDate} ${BRed}]
    ${BCyan}${faintT}|──${resetT}${BRed}[${DGrey} Starting Time ${BRed}]${faintT}${BCyan}──╼${resetT} ${BRed}[${DGrey} ${StartingTime} ${BRed}]
    ${BCyan}${faintT}|
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetIP)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} IP ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetIP} ${DGrey}]
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetDns)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} Dns ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetDns} ${DGrey}]
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetName)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} Name ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetNAME} ${DGrey}]
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetEmail)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} Email ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetEmail} ${DGrey}]
    ${BCyan}${faintT}|──${resetT}${BRed}[ 🎯 ]${BCyan}${faintT}──${resetT}${BRed}[${DGrey}$(FunTargetPhone)${BRed}]${BCyan}${faintT}──╼  ${DGrey}[${BGreen}${slowBlink} Phone ${resetT}${DGrey}]${BYellow}${faintT}─╼${resetT}${LGreen}▰▰▰  ${DGrey}[ ${BGreen}${targetPhone} ${DGrey}]
    ${BCyan}${faintT}|
    ${BCyan}${faintT}└──${resetT}${BRed}[${BCyan} CL ${BRed}]${faintT}${BCyan}──${resetT}${BCyan}╼▰ ${BRed}[${faintT}${BCyan} 🧹 Cleaning Target Variables  🧹 ${BRed}]${BCyan}${faintT}───────╼${resetT}${BCyan}▰▰▰
    ")
    echo "$ToolStatus"
}


AnonMainMenu(){
  while true; do
  #statements
  clear
  # DiabloLogo1
  TargetStatusRun
  KoTHMenuMain=$(echo "${BRed}
          ${BBlue}[${BRed}#${BBlue}] 📜 ${BYellow} Anonimity Surfing Menu

          ${BRed}[${LGrey}1${BRed}]${BBlue} -${DGrey} Anonimity Surfing status
          ${BRed}[${LGrey}2${BRed}]${BBlue} -${DGrey} Anonimity Surfing start
          ${BRed}[${LGrey}3${BRed}]${BBlue} -${DGrey} Anonimity Surfing stop

          ${BBlue}[${BRed}#${BBlue}] 📜 ${BYellow} Network Manager Menu

          ${BRed}[${LGrey}4${BRed}]${BBlue} -${DGrey} ifconfig -a
          ${BRed}[${LGrey}5${BRed}]${BBlue} -${DGrey} ip a

          ${BRed}[${LGrey}x${BRed}]${BWhite} -${DGrey} Exit / Quit / Close


${BCyan}            ┌──${BBlue}[${BBlue} AnLoMinus 👽${BRed} KoTH ${BCyan}$~${BBlue}]
${BCyan}            └──╼ ")
    read -p "$KoTHMenuMain" cmd
    case $cmd in
      1 )
      echo "${BRed}\n\t\t[${LGrey}1${BRed}]${BBlue} -${DGrey} Anonimity Surfing status"
      anonsurf status
      sleep 1
      ;;
      2 )
      echo "${BRed}\n\t\t[${LGrey}2${BRed}]${BBlue} -${DGrey} Anonimity Surfing start"
      anonsurf start
      sleep 1
      ;;
      3 )
      echo "${BRed}\n\t\t[${LGrey}3${BRed}]${BBlue} -${DGrey} Anonimity Surfing stop"
      anonsurf stop
      sleep 1
      ;;
      4 )
      echo "${BRed}\n\t\t[${LGrey}4${BRed}]${BBlue} -${DGrey} Network status (ifconfig -a)"
      ifconfig -a
      sleep 1
      pressEnter
      ;;
      5 )
      echo "${BRed}\n\t\t[${LGrey}5${BRed}]${BBlue} -${DGrey} Network status (ip a)"
      ip a
      sleep 1
      pressEnter
      ;;
      x )
      clear
      break
      ;;
    esac
  done
}

MainMenu(){
  while true; do
  #statements
  clear
  # DiabloLogo1
  TargetStatusRun
  DiabloMenuMain=$(echo "${BRed}
          ${BBlue}[${BRed}#${BBlue}] 📜 Menu

          ${BBlue}[${BRed}#${BBlue}] 📜 Target IP: ${BRed}${targetIP}
          ${BBlue}[${BRed}#${BBlue}] 📜 Target Project Name: ${BRed}${targetNAME}
          ${BBlue}[${BRed}#${BBlue}] 📜 Target Domain Name: ${BRed}${targetDNS}

          ${BRed}[${LGrey}a${BRed}]${BBlue} -${DGrey} Anonymity Surfing
          ${BRed}[${LGrey}1${BRed}]${BBlue} -${DGrey} Planning and Scoping
          ${BRed}[${LGrey}2${BRed}]${BBlue} -${DGrey} Reconnaissance & Vulnerability Assessment
          ${BRed}[${LGrey}3${BRed}]${BBlue} -${DGrey} Gaining Access & Maintaining Access
          ${BRed}[${LGrey}4${BRed}]${BBlue} -${DGrey} Covering tracks
          ${BRed}[${LGrey}5${BRed}]${BBlue} -${DGrey} Analysis & Reporting

          ${BRed}[${LGrey}x${BRed}]${BWhite} -${DGrey} Exit / Quit / Close


${BCyan}            ┌──${BBlue}[${BBlue} AnLoMinus 👽${BRed} Diablo ${BCyan}$~${BBlue}]
${BCyan}            └──╼ ")
    read -p "$DiabloMenuMain" cmd
    case $cmd in
      p|P|plan )
      ReadTargetNameFromtheUser
      ReadTargetIPFromtheUser
      ReadTargetURLFromtheUser
      #
      file="${targetNAME}-Diablo-Log.md"
      if [ -e ${file} ]; then
        t2="$(echo "\n  ${BBlue}[${BRed}!${BBlue}] File Exist! Remove it? [yY/nN]: ")"
        read -p "$t2 " filexist
        case $filexist in
          y|Y)
          echo "  ${BBlue}[${BRed}!${BBlue}] Removing {${targetNAME}-Diablo-Log.md} file .."
          rm ${targetNAME}-Diablo-Log.md
          clear
          exit
          ;;
          n|N)
          echo "  ${BBlue}[${BRed}!${BBlue}] Leaving {${targetNAME}-Diablo-Log.md} file and Add to it .."
          ;;
        esac
      fi
      # Page Header
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo "---" >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " AnLoMinus Diablo PenTest Report $targetNAME " >> ${targetNAME}-Diablo-Log.md
      echo "#### Date: `date`" >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo "---" >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo "# 📜 Menu

      [a] - Anonymity Surfing
      [1] - Planning and Scoping
      [2] - Reconnaissance & Vulnerability Assessment
      [3] - Gaining Access & Maintaining Access
      [4] - Covering tracks
      [5] - Analysis & Reporting

      ┌──[ AnLoMinus 👽 Diablo $~]
      └──╼

      " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo "---" >> ${targetNAME}-Diablo-Log.md
      #  [1] - Planning and Scoping
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo "\n\t\t\t# [1] - Planning and Scoping "
      echo "# [1] - Planning and Scoping " >> ${targetNAME}-Diablo-Log.md
      echo "### Planning Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo "---" >> ${targetNAME}-Diablo-Log.md
      ;;
      a )
      AnonMainMenu
      ;;
      2 )
      clear
      echo "\n\t\t${BRed}[${BBlue}2${BRed}]${BWhite} -${BRed} Reconnaissance & Vulnerability Assessment"

      #  [2] - Reconnaissance & Vulnerability Assessment
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo "# [2] - Reconnaissance & Vulnerability Assessment " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### masscan Scan Log"
      echo "### masscan Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `masscan $targetIP -p0-65535 --max-rate 1000` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### enum4linux Scan Log"
      echo "### enum4linux Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `enum4linux $targetIP` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### nikto Scan Log"
      echo "### masscan Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `nikto -h $targetIP` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### Arp Scan Log"
      echo "### Arp Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `arp -an` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### TraceRoute Scan Log"
      echo "### TraceRoute Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `traceroute $targetIP` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### Ping Scan Log"
      echo "### Ping Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `ping $targetIP -c4` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### Dig Scan Log"
      echo "### Dig Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `dig $targetIP all` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### Nslookup Scan Log"
      echo "### Nslookup Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `nslookup $targetIP` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### WhoIs Scan Log"
      echo "### WhoIs Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `whois $targetIP` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### Nmap Scan Log "
      echo "### Nmap Scan Log [1-5 Min] $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `nmap -sV -sC -O -p- $targetIP ` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### Dnsenum Scan Log "
      echo "### dnsenum Scan Log [1-5 Min] $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `dnsenum $targetDNS ` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### fierce Scan Log "
      echo "### fierce Scan Log [1-5 Min] $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `fierce --domain $targetDNS ` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### DnsRecon Scan Log "
      echo "### dnsrecon Scan Log [1-5 Min] $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `dnsrecon -d $targetDNS ` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      #
      echo "\n\t\t${BGreen}### Dirb Scan Log "
      echo "### Dirb Scan Log $targetIP: " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " `dirb http://$targetDNS` " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md

      #
      echo "---" >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      echo " " >> ${targetNAME}-Diablo-Log.md
      ;;
      3 )
      echo "\n\t\t${BRed}[${BBlue}3${BRed}]${BWhite} -${BRed} Gaining Access & Maintaining Access"
      ;;
      4 )
      echo "\n\t\t${BRed}[${BBlue}4${BRed}]${BWhite} -${BRed} Covering tracks"
      ;;
      5 )
      echo "\n\t\t${BRed}[${BBlue}5${BRed}]${BWhite} -${BRed} Analysis & Reporting"
      ;;
      x )
      clear
      exit
      ;;
    esac
  done
}
# RUN Functions
MainMenu
